# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1319, 859)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TenLuanVan = QtWidgets.QLabel(self.centralwidget)
        self.TenLuanVan.setGeometry(QtCore.QRect(130, 10, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TenLuanVan.setFont(font)
        self.TenLuanVan.setObjectName("TenLuanVan")
        self.SVTH = QtWidgets.QLabel(self.centralwidget)
        self.SVTH.setGeometry(QtCore.QRect(310, 50, 721, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SVTH.setFont(font)
        self.SVTH.setObjectName("SVTH")
        self.linkVideo = QtWidgets.QPushButton(self.centralwidget)
        self.linkVideo.setGeometry(QtCore.QRect(20, 150, 171, 28))
        self.linkVideo.setObjectName("linkVideo")
        self.tachMp4Wav = QtWidgets.QPushButton(self.centralwidget)
        self.tachMp4Wav.setGeometry(QtCore.QRect(20, 210, 171, 28))
        self.tachMp4Wav.setObjectName("tachMp4Wav")
        self.speaker = QtWidgets.QPushButton(self.centralwidget)
        self.speaker.setGeometry(QtCore.QRect(20, 260, 171, 28))
        self.speaker.setObjectName("speaker")
        self.label_linkVideo = QtWidgets.QLabel(self.centralwidget)
        self.label_linkVideo.setGeometry(QtCore.QRect(200, 150, 1091, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_linkVideo.setFont(font)
        self.label_linkVideo.setObjectName("label_linkVideo")
        self.convert = QtWidgets.QGroupBox(self.centralwidget)
        self.convert.setGeometry(QtCore.QRect(10, 320, 211, 241))
        self.convert.setObjectName("convert")
        self.srcFile = QtWidgets.QPushButton(self.convert)
        self.srcFile.setGeometry(QtCore.QRect(10, 30, 171, 28))
        self.srcFile.setObjectName("srcFile")
        self.tgtFile = QtWidgets.QPushButton(self.convert)
        self.tgtFile.setGeometry(QtCore.QRect(10, 70, 171, 28))
        self.tgtFile.setObjectName("tgtFile")
        self.tenKq = QtWidgets.QLineEdit(self.convert)
        self.tenKq.setGeometry(QtCore.QRect(10, 120, 171, 22))
        self.tenKq.setObjectName("tenKq")
        self.convertAudio = QtWidgets.QPushButton(self.convert)
        self.convertAudio.setGeometry(QtCore.QRect(20, 180, 161, 28))
        self.convertAudio.setObjectName("convertAudio")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TenLuanVan.setText(_translate("MainWindow", "HỆ THỐNG CHUYỂN ĐỔI GIỌNG NÓI SỬ DỤNG MÔ HÌNH KHUẾCH TÁN"))
        self.SVTH.setText(_translate("MainWindow", "SINH VIÊN THỰC HIỆN: NGUYỄN VĂN NGUYỄN B1913324 KHMT K45 "))
        self.linkVideo.setText(_translate("MainWindow", "CHỌN VIDEO"))
        self.tachMp4Wav.setText(_translate("MainWindow", "TÁCH VIDEO VÀ ÂM THANH"))
        self.speaker.setText(_translate("MainWindow", "XÁC ĐỊNH SPEAKER"))
        self.label_linkVideo.setText(_translate("MainWindow", "Đường dẫn đến file."))
        self.convert.setTitle(_translate("MainWindow", "CONVERT "))
        self.srcFile.setText(_translate("MainWindow", "CHỌN FILE NGUỒN"))
        self.tgtFile.setText(_translate("MainWindow", "CHỌN FILE NHÃN"))
        self.convertAudio.setText(_translate("MainWindow", "CONVERT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
